### ISSUE TITLE
User should be able to view a header

### ISSUE THREAD

**Issue by bryanfong-dev** [oslabs-beta/protographql#18]
# Tasks
- [ ] Logo top left
- [ ] Project name next to logo
- [ ] Github logo top right (with url)
