### ISSUE TITLE
User should be able to view sidebar 

### ISSUE THREAD

**Issue by bryanfong-dev** [oslabs-beta/protographql#20]
# Task 
Sidebar should have 4 buttons with 4 logos 
- [ ] Schema Button (Tree branch)
- [ ] Code Button ( < / > )
- [ ] Export Button ( Floppy Disk
- [ ] Create Table Button (Plus Sign)
