### ISSUE TITLE
User should have a dialog to welcome them 

### ISSUE THREAD

**Issue by bryanfong-dev** [oslabs-beta/protographql#21]
# Task 
- [ ] Welcome is a Material UI dialog
- [ ] There should be a "start" button which closes the dialog
- [ ] Title " Transform Rest to GraphQL" 
- [ ] Can also have simple instructions
