### ISSUE TITLE
User should be able to view their created tables during the user session

### ISSUE THREAD

**Issue by bryanfong-dev** [oslabs-beta/protographql#23]
# Task 
- [x] Render table components in the "schemaView" File
- [x] Use the dummy data from Main Container to render tables onto the component
- [x] Add 'Edit' button
- [x] Add 'Delete' button
- [x] Reformat tables to render horizontally
