### ISSUE TITLE
Application should be able to translate tables and fields input into a GraphQL schema

### ISSUE THREAD

**Issue by bryanfong-dev** [oslabs-beta/protographql#24]
# Task 
- [x] Application should take the dummy data in Main container and translate into GraphQL 
- [x] Build default GraphQL Object Types Code
- [x] Build default GraphQL Query Type Code
- [x] Build default GraphQL Resolvers Code for Object and Query types
