### ISSUE TITLE
User should be able to add tables when they click the "create table" button

### ISSUE THREAD

**Issue by AlenaBudzko** [oslabs-beta/protographql#39]
# Task
- [x] Add header (table name)
- [x] Fixing sizing issue (Edit/Delete icons, column widths)
- [x] Add an 'Add Field' button
- [x] Add 'Save Changes' or 'Save Table' button
- [x] Wrap table with 'Draggable' component (see WELCOME component for reference)
- [x] Wrap table with 'Dialog' component (see WELCOME component for reference)
