### ISSUE TITLE
User should be able to export files and projects when they click the export button

### ISSUE THREAD

**Issue by AlenaBudzko** [oslabs-beta/protographql#40]
#Task 
- [ ] User should also be able to export the whole project
- [ ] User should be able to export only gql files 
- [ ] User should be able to enter their PostGreSQL creditionals to connect our exported project to their db
- [ ] User should be able to decide where to export the file 
- [ ] User should know that the file is finished downloading (optional if there is no download popup)
